### PR TITLE
Fix Telegram buttons

### LINKED ISSUE #110: Fix Telegram buttons
Now it's impossible to use `reactions.buttons()` with Telegram. Because Telegram Telegram allows only to send keyboard attached to some message.

The idea is to use Telegram's `editMessageReplyMarkup` appending inline buttons to the previous message sent to the channel.

### PR DESCRIPTION
**Pull request by morfeusys**
fixes #110

### CODE REVIEW

File: examples/hello-world/src/main/kotlin/com/justai/jaicf/examples/helloworld/channel/Telegram.kt [hunk 1]
```diff
@@ -4,5 +4,5 @@ import com.justai.jaicf.channel.telegram.TelegramChannel
 import com.justai.jaicf.examples.helloworld.helloWorldBot
 
 fun main() {
-    TelegramChannel(helloWorldBot, "580468601:AAHaMg4gOsN2A_zvIO6-PouVk3GcZ_WVrdI").run()
+    TelegramChannel(helloWorldBot, "580468601:AAFZaIXLiKbD7XRsGVHX74N-5nlXbttvEzc").run()
```
Comment (Denire) [inline examples/hello-world/src/main/kotlin/com/justai/jaicf/examples/helloworld/channel/Telegram.kt:7]: Is it a real token?
Maybe we should host a bot somewhere (heroku/jaicp cloud) with this token to be a demo for users, what do you think?

Comment (morfeusys) [reply examples/hello-world/src/main/kotlin/com/justai/jaicf/examples/helloworld/channel/Telegram.kt:7]: I don't think so

**Review by Denire — APPROVED** [review]

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt [hunk 2]
```diff
@@ -18,11 +19,34 @@ class TelegramReactions(
 ) : Reactions() {
 
     val chatId = request.chatId
+    private val messages = mutableListOf<Message>()
```
Comment (nikvoloshin) [inline channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:22]: should we really store all previous responses instead of the last one?

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt [hunk 3]
```diff
@@ -18,11 +19,34 @@ class TelegramReactions(
...
+        pair.first?.body()?.result?.let { messages.add(it) }
+    }
 
     override fun say(text: String): SayReaction {
         return sendMessage(text)
     }
 
+    override fun buttons(vararg buttons: String): ButtonsReaction {
+        messages.lastOrNull()?.let { message ->
+            val keyboard = message.replyMarkup?.inlineKeyboard?.toMutableList() ?: mutableListOf()
```
Comment (nikvoloshin) [inline channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:34]: As I see, `kotlin-telegram-bot` supports only inline keyboard, but it'd be better to support basic telegram `ReplyKeyboard`
(not much related to this PR, just thoughts for the future)

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt [hunk 4]
```diff
@@ -18,11 +19,34 @@ class TelegramReactions(
...
+            keyboard.addAll(buttons.map { listOf(InlineKeyboardButton(it, callbackData = it)) })
+
+            api.editMessageReplyMarkup(
+                    chatId,
+                    message.messageId,
+                    replyMarkup = InlineKeyboardMarkup(keyboard)
+            ).also {
+                messages.remove(message)
```
Comment (nikvoloshin) [inline channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:42]: Maybe change it to `messages.removeIf { it.messageId == message.messageId }`?
`Message` is a huge data class with a lot fields, nested data classes, etc.
I'd not rely on Message's `equals`

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt [hunk 5]
```diff
@@ -84,7 +109,16 @@ class TelegramReactions(
         replyToMessageId: Long? = null,
         replyMarkup: ReplyMarkup? = null
     ): ImageReaction {
-        api.sendPhoto(chatId, url, caption, parseMode, disableNotification, replyToMessageId, replyMarkup)
+        api.sendPhoto(
```
Comment (nikvoloshin) [inline channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:112]: Let's put all parameters on one line for consistency with others `send*` methods

**Review by nikvoloshin — CHANGES_REQUESTED** [review]

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt (hunk 2 above)
Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:22]: @nikvoloshin nope, we shouldn't. But this is the way to edit any of sent message once we've started to use editors.

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt (hunk 3 above)
Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:34]: Telegram allows attaching only inline buttons editing the message. The user [must pass keyboard](https://core.telegram.org/bots#keyboards) with the message to display a "basic" keyboard.

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt [hunk 6]
```diff
@@ -18,11 +19,34 @@ class TelegramReactions(
...
+                    chatId,
+                    message.messageId,
+                    replyMarkup = InlineKeyboardMarkup(keyboard)
+            ).also {
+                messages.remove(message)
+                addResponse(it)
+            }
+        }
+
+        return ButtonsReaction.create(buttons.asList())
```
Comment (nikvoloshin) [inline channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:47]: If there is no previous response (i.e. `messages.lastOrNull == null`) and we are unable to send buttons, we anyway will log the `ButtonReaction`. Is this the desired behavior?

**Review by nikvoloshin — CHANGES_REQUESTED** [review]

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt (hunk 3 above)
Comment (nikvoloshin) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:34]: Yes, you are right, thanks

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt (hunk 6 above)
Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:47]: Like for any other channel we cannot be sure that buttons was rendered successfully. And nevertheless we register buttons response as a content that was generated by scenario.

Comment (nikvoloshin) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:47]: Default implementations of `Reactions` methods don't register reactions, they just create them. So if a channel doesn't support some kind of response (and so doesn't override the method), the reaction will not be registered. So I think this is the case.

Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:49]: `Reacion` has an internal constructor and could be created with `create` factory only. My point was about other channels - we cannot guarantee that some components (like buttons) will be rendered actually but nevertheless register the output..

Comment (nikvoloshin) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramReactions.kt:49]: Ah, yes, you are right about a constructor, I missed it. 
But, anyway, when we can't guarantee that responses will not be rendered on a 3rd party side - it's okay to register them in order to tell a user that we've done all required work on the framework side.
But in the current case, the channel knows for sure that the reaction will not be even processed somehow, so in this case, the channel should not register the reaction, otherwise, it will lead to confusion for the user.
I'd suggest creating an issue for that after merge.

File: channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramBotRequest.kt [hunk 7]
```diff
@@ -26,30 +26,33 @@ interface TelegramBotRequest: BotRequest {
...
 ): TelegramBotRequest, EventBotRequest(
-    clientId = message.chat.id.toString(),
+    clientId = message.clientId,
     input = TelegramEvent.CONTACT
-)
\ No newline at end of file
+)
+
+internal val Message.clientId
+    get() = from?.id?.toString() ?: chat.id.toString()
```
[the remark this answers is not in the document]
Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramBotRequest.kt]: Could you please describe these cases?

[the remark this answers is not in the document]
Comment (morfeusys) [reply channels/telegram/src/main/kotlin/com/justai/jaicf/channel/telegram/TelegramBotRequest.kt]: Decided to rollback to chat id

**Review by nikvoloshin — APPROVED** [review]
